"use client";
import { useState, useRef } from "react";
import { Download, FileText, Loader2 } from "lucide-react";
import type { PredictionResult, LoanApplication } from "@/lib/api";

interface Props {
  result:      PredictionResult;
  application: LoanApplication;
}

export default function ExportButton({ result, application }: Props) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);

    // Dynamically import jsPDF + html2canvas
    const [{ jsPDF }, { default: html2canvas }] = await Promise.all([
      import("jspdf"),
      import("html2canvas"),
    ]);

    // Build a hidden HTML snippet to capture
    const div = document.createElement("div");
    div.style.cssText = `
      position:fixed; top:-9999px; left:-9999px; width:600px; padding:40px;
      font-family:'Inter',sans-serif; background:#111827; color:#f0f6ff; border-radius:16px;
    `;
    div.innerHTML = `
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:24px;">
        <div style="width:40px;height:40px;border-radius:10px;background:linear-gradient(135deg,#059669,#0d9488);display:flex;align-items:center;justify-content:center;">
          <span style="color:#fff;font-size:20px">📈</span>
        </div>
        <div>
          <h1 style="margin:0;font-size:22px;font-weight:800;">LoanLogic AI Assessment</h1>
          <p style="margin:0;font-size:12px;color:#9ca3af;">${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}</p>
        </div>
      </div>

      <div style="padding:20px;border-radius:12px;background:${result.status === "Approved" ? "rgba(16,185,129,0.12)" : "rgba(239,68,68,0.12)"};border:1px solid ${result.status === "Approved" ? "rgba(16,185,129,0.3)" : "rgba(239,68,68,0.3)"};text-align:center;margin-bottom:20px;">
        <p style="font-size:32px;font-weight:900;margin:0;color:${result.status === "Approved" ? "#34d399" : "#f87171"};">${result.status === "Approved" ? "✓" : "✗"} ${result.status}</p>
        <p style="margin:8px 0 0;color:#9ca3af;font-size:14px;">Approval Confidence: <strong style="color:#34d399;">${Math.round(result.confidence_score * 100)}%</strong></p>
      </div>

      <h3 style="margin:0 0 12px;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Application Details</h3>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        ${[
          ["Income ($/mo)",     `$${application.ApplicantIncome.toLocaleString()}`],
          ["Co-applicant ($/mo)",`$${application.CoapplicantIncome.toLocaleString()}`],
          ["Loan Amount",       `$${application.LoanAmount}K`],
          ["Loan Term",         `${application.Loan_Amount_Term} months`],
          ["Credit History",    application.Credit_History === 1 ? "Good" : "Poor"],
          ["Property Area",     application.Property_Area],
          ["Education",         application.Education],
          ["Employment",        application.Self_Employed === "Yes" ? "Self-employed" : "Employed"],
          ["Monthly EMI (Est.)",`$${result.emi_estimate.toLocaleString("en-US", { maximumFractionDigits: 0 })}`],
        ].map(([k, v], i) => `
          <tr style="background:${i % 2 === 0 ? "rgba(255,255,255,0.04)" : "transparent"}">
            <td style="padding:8px 12px;color:#9ca3af;">${k}</td>
            <td style="padding:8px 12px;font-weight:600;text-align:right;">${v}</td>
          </tr>`).join("")}
      </table>

      <h3 style="margin:20px 0 10px;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Key Decision Factors</h3>
      ${result.key_factors.map(f => `
        <div style="margin-bottom:8px;padding:10px 14px;border-radius:8px;background:${
          f.impact === "positive" ? "rgba(16,185,129,0.08)" : f.impact === "negative" ? "rgba(239,68,68,0.08)" : "rgba(245,158,11,0.08)"
        };border:1px solid ${
          f.impact === "positive" ? "rgba(16,185,129,0.2)" : f.impact === "negative" ? "rgba(239,68,68,0.2)" : "rgba(245,158,11,0.2)"
        };">
          <strong style="font-size:13px;color:${f.impact === "positive" ? "#34d399" : f.impact === "negative" ? "#f87171" : "#fbbf24"};">${f.factor}</strong>
          <p style="margin:4px 0 0;font-size:12px;color:#9ca3af;">${f.detail}</p>
        </div>`).join("")}

      <p style="margin-top:24px;font-size:11px;color:#4b5563;text-align:center;">
        Generated by LoanLogic AI • AI-powered prediction (for informational purposes only)
      </p>
    `;

    document.body.appendChild(div);

    try {
      const canvas = await html2canvas(div, {
        scale: 2, backgroundColor: "#111827", useCORS: true, logging: false
      });
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const imgW = 210;
      const imgH = (canvas.height * imgW) / canvas.width;
      pdf.addImage(canvas.toDataURL("image/png"), "PNG", 0, 0, imgW, imgH);
      pdf.save(`LoanLogic_AI_Assessment_${new Date().toISOString().slice(0, 10)}.pdf`);
    } finally {
      document.body.removeChild(div);
      setExporting(false);
    }
  }

  return (
    <button
      id="export-pdf-btn"
      onClick={handleExport}
      disabled={exporting}
      className="btn-primary flex items-center gap-2 text-sm px-4 py-2.5"
      style={{ background: "linear-gradient(135deg, #059669, #10b981)", boxShadow: "0 4px 15px rgba(16,185,129,0.35)" }}
    >
      {exporting
        ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating PDF…</>
        : <><Download className="w-4 h-4" /><FileText className="w-4 h-4" /> Export Assessment</>}
    </button>
  );
}
